### ISSUE TITLE
Add Response DAO for getPitch API

### ISSUE THREAD

**Issue by souptik4572** [souptik4572/Xharktank-SpringBoot#2]
The getPitch API currently handles the response directly in the service layer. We should create a Response DAO to handle the response creation, status codes, and result messages.

This will improve separation of concerns and make the API response handling more reusable.

Steps:

1. Create a ResponseDAO class
2. Add method for success response:
   - createSuccessResponse(data, message)
   - Returns response with 200 status code and result message 
3. Add method for error response:
   - createErrorResponse(message, statusCode)
   - Returns response with status code and error message
4. Update getPitch API endpoint:
   - On success, return ResponseDAO.createSuccessResponse(pitch, "Pitch fetched successfully") 
   - On error, return ResponseDAO.createErrorResponse("Error fetching pitch", 500)
5. Reuse ResponseDAO for other APIs

This encapsulates API response handling including status codes, result messages, and errors.

**Comment by youngInnovator** [comment]
Saving response in database is not required, especially if we are not saving anything else other than status code and already retrieved data from DB, So I will suggest to use directly response wrapper instead of DAO layer.

**Comment by souptik4572** [comment]
This implementation is mainly for sending the API response and not saving the response object in the DB. Right now only the raw data from the service class is being sent as a response in the getPitch API. I basically wanted it to be encapsulated in a structured Response object having the status code and the success/error message and other details if applicable.

**Comment by youngInnovator** [comment]
100% agreed. if we are are not saving object in Db, DAO layer is not require and we can use Spring response handler or our custom wrapper around response from service layer.

**Comment by youngInnovator** [comment]
I am working on this issue, created PR but I noticed wrapper already introduced so fixing my code changes according to already introduced wrapper
