### ISSUE TITLE
Add Response DAO for getAllPitches API

### ISSUE THREAD

**Issue by souptik4572** [souptik4572/Xharktank-SpringBoot#3]
The getAllPitches API currently handles the response directly in the service layer. We should create a Response DAO to handle the response creation, status codes, and result messages.

This will improve separation of concerns and make the API response handling more reusable.

Steps:

1. Create a ResponseDAO class
2. Add methods:
   - createSuccessResponse(data, message) 
     - Returns 200 response with result message
   - createEmptySuccessResponse(message)
     - Returns 200 with empty data and message 
   - createErrorResponse(message, statusCode)
     - Returns error response
3. Update getAllPitches API endpoint (sample messages attached below):
   - If pitches found, return ResponseDAO.createSuccessResponse(pitches, "Pitches fetched successfully")
   - If no pitches, return ResponseDAO.createEmptySuccessResponse("No pitches found") 
   - On error, return ResponseDAO.createErrorResponse("Error fetching pitches", 500)
4. Reuse ResponseDAO for other APIs

This encapsulates status codes, result messages for success/empty/error scenarios.

**Comment by NyorJa** [comment]
hi @souptik4572 , please assign this to me

**Comment by souptik4572** [comment]
Sure @NyorJa, please go ahead.
